name: Publish Python Package to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi # This should match the environment name you provided in GitHub

    permissions:
      id-token: write # This is required for OpenID Connect
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      run: python -m pip install uv

    - name: Install project dependencies with uv
      run: |
        # Install main dependencies first
        uv pip install --system .
        # Then install dev dependencies
        uv pip install --system ".[dev]"
        # Verify structlog is installed
        python -c "import structlog; print(f'structlog version: {structlog.__version__}')"

    - name: Install build and twine
      run: python -m pip install build twine

    - name: List installed packages (debug)
      run: pip list | grep -E "(structlog|pytest)"

    - name: Run tests
      env:
        PYTHONPATH: src
      run: |
        pytest

    - name: Build and publish
      run: |
        python -m build
        twine upload --repository pypi dist/*